---
spring:
  profiles: real_db
  datasource:
    url: jdbc:mariadb://database-1.cbfdivene2cw.ap-northeast-2.rds.amazonaws.com:3306/ssooya_springboot_webservice
    username: ssooya90
    password: 04021015
    driver-class-name: org.mariadb.jdbc.Driver